version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: wonderland-database
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - mysql
    restart: always

#  wonderlandbe:
#    container_name: wonderland-be
#    image: wonderlandbe:v1
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 80:8080
#      - 8787:8787

networks:
  mysql:
    driver: bridge

volumes:
  mysql-volume: